.gitignore
Test modification (added .autoenv* to .gitignore) for testing dev publishing.
=> Added .autoenv* to gitignore.

pages/lafires/index.html
Added comment to index.html to test dev pipeline.
=> Added visible comment to index.html to test publishing.

pages/lafires/start-your-recovery.html
Remove periods from links per [Google doc](https://docs.google.com/document/d/1_qt3b3f59yAJzXz-14Y59UIJ8m4WcgBO_fFBHqTSpWo/edit?tab=t.0)
Related PR: https://github.com/Office-of-Digital-Services/cagovportal/pull/1132
=> 1074 sync remove periods

pages/lafires/get-help-online.html
For https://github.com/Office-of-Digital-Services/cagovportal/issues/1150
Add 3 new cards with Mental health links
=> Add new cards for mental health

src/_data/airTable.json
Ran update data command to get new json data for service finder
=> Updated service finder data with latest

pages/lafires/get-help-online.html
Remove extra text and characters
Fix for https://github.com/Office-of-Digital-Services/cagovportal/issues/1150#issuecomment-2738270129
=> Remove duplicate text and carat

src/root/web.config
Reverts Office-of-Digital-Services/cagovportal-lafires#73
=> Revert "fixing redirect case"

README.md, pages/404.html, pages/lafires/index.html, src/_data/breadcrumbs.cjs, src/_data/dynamic_sidenav.json, src/root/index.html, src/root/web.config
Reverts Office-of-Digital-Services/cagovportal-lafires#72
=> Revert "LAfires url redirect"

pages/lafires/cleanup-and-debris-removal.html, pages/lafires/index.html, src/_data/airTable.json
All updates requested to main
1. Update wording in application deadlines section on homepage
2. Update debris removal (DR) date from March 31 > April 15 in all instances
3. Update service finder data which has new DR date
This PR will fix the following issues
1. https://github.com/Office-of-Digital-Services/cagovportal/issues/1015
2. https://github.com/Office-of-Digital-Services/cagovportal/issues/1056
3. https://github.com/Office-of-Digital-Services/cagovportal/issues/975
=> 1056 3 28 updates mark

pages/lafires/index-shared.html, src/_data/i18n/i18n-home.json, src/_data/i18n/i18n-service-finder.json
Updated text on homepage, service-finder.
=> Debris removal corrections.

src/_data/i18n/i18n-home.json
Updated a paragraph on homepage for title consistency.
=> Updated a paragraph on homepage for title consistency.

pages/lafires/cleanup-and-debris-removal-shared.html
Fixed unrepaired conflict on cleanup and removal.
=> Fixed unrepaired conflict on cleanup and removal.

src/_data/i18n/i18n-cleanup.json, src/_data/i18n/i18n-help-business.json, src/_data/i18n/i18n-plan-visit.json, src/_data/i18n/i18n-start-your-recovery.json, src/_data/i18n/i18n-steps.json
Translations of newly added text.
=> jbum Translations 2025 04 02

pages/lafires/en/en.json, src/_includes/layouts/base.html
Added meta locale tag.  Differentiate between English lang (en) and locale (en-US).
=> Added meta locale tag.

pages/lafires/en/en.json
Fix broken links on home page.  Due to a recent change on English locale.
=> Fix broken links on home page.  Due to a recent change on English locale.

src/_data/i18n/i18n-help-online.json, src/_includes/get-help-online-shared.html
Add this new section to get-help-online per [google](https://docs.google.com/document/d/1qwNXAJZ4D3FBzXzL0ZDmPgnoTVFWy7QBBLrVFyIJruQ/edit?tab=t.0)
=> Get help add low income mso

eleventy.config.cjs, src/root/web.config
- homepage case for /LAfires/, mostly for "English" link
- redirecting "*/index.html" to "/"
- redirecting "*-shared/" to "/"
=> SEO - link maintenance

src/_data/i18n/i18n-financial-assistance.json, src/_includes/financial-assistance-shared.html
Second try - added missing json file.
=> Tokenize financial assistance 2

src/root/web.config
redirect
https://www.test-cagov.cdt.ca.gov/lafires/stay-healthy/
to
https://www.test-cagov.cdt.ca.gov/lafires/help-for-you/health-and-safety/
=> redirect stay-healthy to test

src/root/web.config
Reverting the Redirects for now.  There are more rules at the routing level that need to be configured.
=> Revert "TEST - LA fires root variation redirects"

src/root/web.config
- removing rebots redirect (not used on subfolder site)
- Adding 410 for French pages
- Changing order to have 410s first
=> TEST - 410 for french pages - reordering redirects

src/root/web.config
- Moving 410 rules to top
- Adding 410 rule for French pages
- Removing robots.txt rule, since it only applies to root project
=> SEO - 410s for french and reorder rules

src/_data/i18n/i18n-service-finder.json, src/_includes/recovery-services-all-shared.html, src/_includes/recovery-services-finder-results.html.js, src/_includes/recovery-services-finder-shared.html
- also removing Bootstrap dismiss
=> Service finder - adding translations

src/_data/i18n/i18n-track-progress.json, src/_includes/track-progress-shared.html
=> 1153 june 11 release track las recovery

src/_includes/see-real-time-info-shared.html
Fixes [#312](https://github.com/Office-of-Digital-Services/cagovportal-lafires/issues/312)
=> Fix broken link  on see real time info page for water quality

src/_data/i18n/i18n-real-time.json, src/_includes/see-real-time-info-shared.html
Did these in test, rebranching from main to not bring over other test commits
=> Replace state water resources control board with the los angeles regional water quality control board, fix broken link on Environment>water

src/root/web.config
Reverts Office-of-Digital-Services/cagovportal-lafires#358
=> Revert "TEST - SEO - using single slash match, update 1"

src/_data/i18n/i18n-replace-documents.json, src/_data/i18n/i18n-vital-records.json, src/_includes/birth-certificates-shared.html, src/_includes/death-certificates-shared.html, src/_includes/marriage-certificates-shared.html
Make a number of updates to the vital records pages, including:
- update content, phrasing
- change top navigation to split out mail and email
- remove apply in person section
=> Feature: sept 25 vital records content updates 
